project:
  type: website
  output-dir: docs
  title: "OzFlux Tower Handbook"

website:
  navbar:
    left:
      - text: Home
        file: Home.md
      - text: Climbing & Rigging
        file: ClimbingRigging.md
      - text: Enclosures
        file: Enclosures.md
      - text: Tower Types
        file: Tower-types.md

format:
  html:
    theme: cosmo
    toc: true
