project:
  type: website
  output-dir: docs
  title: "OzFlux Tower Handbook"

website:
  sidebar:
    contents:
      - text: Home
        file: Home.md
      - text: Communication
        file: Communication.md
      - text: OpenVPN
        file: TERNOpenVPN.md
      - text: Climbing & Rigging
        file: ClimbingRigging.md
      - text: Tower Types
        file: Tower-types.md
      - text: Enclosures
        file: Enclosures.md
      - text: Sensors
        file: Sensorwiring.md
     
      
format:
  html:
    theme: cosmo
    toc: true
