project:
  type: website
  output-dir: docs
  title: "OzFlux Tower Handbook"

author: "Markus Loew"

website:
  sidebar:
    contents:
      - text: Home
        file: Home.md
      - text: Tower Types
        file: Towers.md
      - section: "Communication, networking, telemetry"
        contents:
        - text: Communication
          file: Communication.md
        - text: OpenVPN
          file: TERNOpenVPN.md
        - text: OzFlux Networking
          file: OzFluxnetwork.md
        - text: Data transfer
          file: Datatransfer.md
      - text: Climbing & Rigging
        file: ClimbingRigging.md
      - text: Power
        file: power.md
      - text: Enclosures
        file: Enclosures.md
      - section: "Sensors"
        contents:
        - text: Sensors and their wiring
          file: Sensorwiring.md
        - text: SDI12 sensors
          file: SDI12sensors.md
        - text: Sensor calibration
          file: Sensorcalibration.md
        - text: Phenocam
          file: Phenocam.md
      - text: Tips and Tricks
        file: tips.md
format:
  html:
    theme: cosmo
    toc: true